### ISSUE TITLE
Feature Request: "Disabled Buffers" rather than "Disabled Files"

### ISSUE THREAD

**Issue by anoduck** [gorbit99/codewindow.nvim#44]
More than likely you are already working on this for the rewrite, and if that is the case, you can just give a thumbs up.

Code window is opening in buffers where it is not supposed to, and sometimes makes those buffers unusable. Because they are buffers without a file type, the user is unable to disable them via the `exclude_filetypes` configuration variable. So my suggestion is to configure via a `exclude_buffers` variable instead of the `exclude_filetype` variable.

Not the most creative suggestion, just an obvious one.

**Comment by gorbit99** [comment]
Actually not working on a solution to this, as my stance was, that if a plugin's buffer doesn't have a filetype and should be ignored, that should be a feature request on that plugins repository. This is mainly because this sort of plugin interaction is qutie commonplace and should be supported from both sides for it to work.

But maybe this issue isn't about plugins, what scenario are you running into that exclude_filetype can't help with?

**Comment by anoduck** [comment]
Nvim-Tree and Trouble, are two of the biggest culprits at this moment. The variable `exclude_filetypes` in my `init.lua looks like:

```lua
exclude_filetypes = {'alpha', 'Trouble', 'packer', 'neorg', 'norg', 'Telescope', 'NvimTree'}, 
```

**Comment by gorbit99** [comment]
Hmm, both of those should work, they have filetypes, and those seem correct. They are still causing issues even after that?

**Comment by anoduck** [comment]
`NeoTree` was also a part of that list, but is not currently installed, and I removed it when I went to post it here as part of routine tidiness. Now, I cannot get it to reproduce the errors... Wouldn't that be my luck?

 Oh, fiddlesticks.

I will close this one out, and if they rear their terrifying head again, I will let you know.
Thanks for working with me. You're an alright feller. :+1:

**Comment by gorbit99** [comment]
My guess is that you didn't compile the config file maybe? I mean if you're using packer. Anyways, I'm glad it's fixed!
